version = 0.1
[default.deploy.parameters]
stack_name = "loan-prediction-app"
resolve_s3 = true
s3_prefix = "loan-prediction-app"
region = "us-east-1"
profile = "AdministratorAccess-715841371411"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
